# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

# 工作流名称
name: Xiaobei

on:
  # 提交主分支触发
  push:
    branches: [ main ]
  # 定时触发
  schedule:
    # - cron: "30 0 * * *"
    # 每天九点
    - cron: "0 1 * * *"

# 工作任务
jobs:

  run-xiaobei:

    # 最新Ubuntu
    runs-on: ubuntu-latest

    # 任务步骤
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: 3.9

        # 安装requests依赖
      - name: install requests
        run: |
          python -m pip install requests

        # 运行 main.py
      - name: run main.py
        # 环境变量
        env:
          # 必填
          XB_USERNAME: ${{ secrets.XB_USERNAME }}
          # 必填
          XB_PASSWORD: ${{ secrets.XB_PASSWORD }}
          # 必填
          XB_LOCATION: ${{secrets.XB_LOCATION}}
          # 选填
          XB_COORD: ${{secrets.XB_COORD}}
          # 选填 填则通知，不填则不通知
          XB_WXAPP: ${{secrets.XB_WXAPP}}
          # 选填 填则通知，不填则不通知
          XB_EMAIL: ${{secrets.XB_EMAIL}}
        run: |
          python3.9 main.py
